# Generated by Django 5.0.2 on 2024-02-21 07:54



from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="portfolio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=255)),
                ("field", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("number", models.IntegerField()),
                ("video_title", models.CharField(max_length=500)),
                ("video_url", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("img_path", models.CharField(max_length=255)),
            ],
        ),
    ]
