# Generated by Django 5.0.2 on 2024-04-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="video_title",
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="field",
            field=models.IntegerField(choices=[(1, "기업홍보"), (2, "제품홍보"), (3, "브이로")]),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="img_path",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
