# Generated by Django 5.0.2 on 2024-04-17 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_portfolio_field_alter_portfolio_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolio",
            options={"ordering": ["number", "created_at"]},
        ),
    ]
